# Read the Docs configuration file for Homodyne Analysis
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # Install system dependencies for documentation
  apt_packages:
    - graphviz        # For Sphinx diagrams
    - pandoc          # For MyST markdown processing
    - latexmk         # For LaTeX/PDF output
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
  
  # Build environment setup
  jobs:
    pre_create_environment:
      # Set environment variables for reproducible builds
      - export READTHEDOCS_BUILD=true
      - export PYTHONWARNINGS="ignore::UserWarning,ignore::DeprecationWarning"
    post_create_environment:
      # Upgrade build tools
      - pip install --upgrade pip setuptools wheel
    post_install:
      # Install package with documentation dependencies
      - pip install -e ".[docs,dev]"
      # Install additional documentation tools
      - pip install sphinx-autobuild sphinx-rtd-theme

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false  # Set to true after fixing all warnings

# Build additional formats
formats:
  - pdf
  - epub

# Configure Python environment
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - dev
  
  # Use system site packages for better dependency resolution
  system_site_packages: false

# Exclude version control and unnecessary files from build
submodules:
  exclude: all

# Configure search ranking
search:
  ranking: 
    "user-guide/quickstart.html": 10
    "user-guide/installation.html": 9
    "api/index.html": 8
    "user-guide/configuration.html": 7
    "examples/": 6
    "developer-guide/": 4

# Redirects for moved/renamed pages (maintains external links)
redirects:
  "quickstart.html": "user-guide/quickstart.html"
  "installation.html": "user-guide/installation.html"
  "api.html": "api/index.html"
