# Read the Docs configuration file for Homodyne v2.22.1
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
  # Allow warnings during build (intersphinx offline, etc.)
  fail_on_warning: false

formats:
  - pdf
  - epub

# Submodules (if any)
submodules:
  include: []
  recursive: false
