# Homodyne v2 Minimal Configuration: Static Isotropic Analysis
# =============================================================
# Minimal working configuration for static isotropic diffusion analysis.
# 3-parameter model: D₀, α, D_offset
# 
# This template contains only the REQUIRED sections and parameters
# needed for basic homodyne analysis to work.

# REQUIRED: Analysis mode specification
analysis_mode: "static_isotropic"

# REQUIRED: Core physics parameters for analysis
analyzer_parameters:
  # Time step between correlation measurements (seconds)
  dt: 0.1
  
  # Frame range for analysis  
  start_frame: 1
  end_frame: 1000

# REQUIRED: Data file locations
experimental_data:
  # Path to directory containing data files
  data_folder_path: "./data/sample/"
  
  # HDF5 data file name
  data_file_name: "your_data.hdf"
  
  # Optional: Phi angles file (defaults to auto-detection from data)
  phi_angles_path: "./data/phi_angles/"
  phi_angles_file: "phi_list.txt"

# REQUIRED: Analysis mode settings
analysis_settings:
  # Enable static mode (vs laminar flow)
  static_mode: true
  
  # Static submode: "isotropic" for single-angle analysis
  static_submode: "isotropic"

# REQUIRED: Initial parameter values
initial_parameters:
  # Parameter names for 3-parameter static isotropic model
  parameter_names: ["D0", "alpha", "D_offset"]
  
  # Initial values for optimization
  values: [1.0e-6, 0.8, 1.0e-8]
  
  # Optional: specify which parameters to optimize (defaults to all)
  # active_parameters: ["D0", "alpha", "D_offset"]

# REQUIRED: V2 optimization configuration
optimization:
  # Variational Inference (primary method)
  vi:
    enabled: true
    max_iterations: 1000
    learning_rate: 0.01
    convergence_tolerance: 1e-6
  
  # MCMC sampling (for uncertainty quantification)
  mcmc:
    enabled: true
    num_samples: 2000
    num_warmup: 1000
    num_chains: 4

# OPTIONAL: Parameter bounds and constraints
parameter_space:
  bounds:
    - name: D0
      min: 1.0
      max: 1000000.0
      type: TruncatedNormal
      prior_mu: 10000.0
      prior_sigma: 1000.0
      unit: Å²/s

    - name: alpha
      min: -2.0
      max: 2.0
      type: Normal
      prior_mu: -1.5
      prior_sigma: 0.1
      unit: dimensionless

    - name: D_offset
      min: -100
      max: 100
      type: Normal
      prior_mu: 0.0
      prior_sigma: 10.0
      unit: Å²/s

# OPTIONAL: Basic logging configuration
logging:
  enabled: true
  level: "INFO"
  console:
    enabled: true
  file:
    enabled: false

# OPTIONAL: Metadata
metadata:
  config_version: "2.0"
  description: "Minimal static isotropic configuration"
  analysis_mode: "static_isotropic"
  parameter_count: 3