# Homodyne v2 Standard Configuration Template
# ==========================================
# Comprehensive configuration template with commonly used options.
# Suitable for most homodyne XPCS analysis workflows.
# 
# This template includes required parameters plus frequently used
# optional features for enhanced analysis capabilities.

# REQUIRED: Analysis mode specification
analysis_mode: "static_isotropic"

# REQUIRED: Core physics parameters for analysis
analyzer_parameters:
  # Time step between correlation measurements (seconds)
  dt: 0.1
  
  # Frame range for analysis  
  start_frame: 1
  end_frame: 1000
  
  # Optional: nested structure support
  temporal:
    dt: 0.1
    start_frame: 1
    end_frame: 1000
  
  scattering:
    wavevector_q: 0.0054
  
  geometry:
    stator_rotor_gap: 2000000

# REQUIRED: Data file locations
experimental_data:
  # Path to directory containing data files
  data_folder_path: "./data/SAMPLE_NAME/"
  
  # HDF5 data file name
  data_file_name: "your_data.hdf"
  
  # Phi angles configuration
  phi_angles_path: "./data/phi_angles/"
  phi_angles_file: "phi_list.txt"
  
  # Caching configuration
  cache_file_path: "./data/SAMPLE_NAME/"
  cache_filename_template: "cached_c2_frames_{start_frame}_{end_frame}.npz"
  cache_compression: true
  
  # Data format options
  data_type: "float64"
  file_format: "HDF5"

# REQUIRED: Analysis mode settings
analysis_settings:
  # Enable static mode (vs laminar flow)
  static_mode: true
  
  # Static submode: "isotropic" or "anisotropic"
  static_submode: "isotropic"
  
  # Model description
  model_description:
    type: "static_diffusion"
    parameters: 3

# REQUIRED: Initial parameter values
initial_parameters:
  # Parameter names (3 for static, 7 for laminar flow)
  parameter_names: ["D0", "alpha", "D_offset"]
  
  # Initial values for optimization
  values: [1.0e-6, 0.8, 1.0e-8]
  
  # Active parameters (defaults to all if not specified)
  active_parameters: ["D0", "alpha", "D_offset"]

# REQUIRED: V2 optimization configuration
optimization:
  # Variational Inference (primary method)
  vi:
    enabled: true
    max_iterations: 1000
    learning_rate: 0.01
    convergence_tolerance: 1e-6
    batch_size: "auto"
  
  # MCMC sampling (for uncertainty quantification)
  mcmc:
    enabled: true
    num_samples: 2000
    num_warmup: 1000
    num_chains: 4
    target_accept_prob: 0.8
  
  # Hybrid VI→MCMC pipeline
  hybrid:
    enabled: true
    vi_initialization: true
    vi_samples_for_init: 500
    mcmc_refinement: true

# Optimization method configuration
optimization_config:
  # Angle filtering
  angle_filtering:
    enabled: false  # Disabled for isotropic
    target_ranges: []
    fallback_to_all_angles: true
  
  # Classical optimization fallback
  classical_optimization:
    enabled: false
    methods: ["nelder_mead"]

# Parameter bounds and constraints
parameter_space:
  bounds:
    - name: D0
      min: 1.0
      max: 1000000.0
      type: TruncatedNormal
      prior_mu: 10000.0
      prior_sigma: 1000.0
      unit: Å²/s

    - name: alpha
      min: -2.0
      max: 2.0
      type: Normal
      prior_mu: -1.5
      prior_sigma: 0.1
      unit: dimensionless

    - name: D_offset
      min: -100
      max: 100
      type: Normal
      prior_mu: 0.0
      prior_sigma: 10.0
      unit: Å²/s

# Comprehensive logging configuration
logging:
  enabled: true
  level: "INFO"
  
  console:
    enabled: true
    level: "INFO"
    format: "detailed"
    colors: true
  
  file:
    enabled: true
    level: "DEBUG"
    path: "./logs/"
    filename: "homodyne_analysis.log"
    max_size_mb: 10
    backup_count: 3
  
  performance:
    enabled: true
    level: "INFO"
    threshold_seconds: 0.1

# Performance settings
performance_settings:
  enable_jit: true
  enable_gpu: false  # Auto-detected
  memory_optimization: true
  parallel_processing: true
  cache_strategy: "intelligent"

# Validation rules
validation_rules:
  data_quality:
    check_data_range: true
    correlation_minimum: 0.0
    correlation_maximum: 2.0
  
  parameter_validation:
    check_bounds: true
    warn_on_extreme_values: true
  
  convergence_checks:
    enabled: true
    tolerance: 1e-6

# Metadata
metadata:
  config_version: "2.0"
  description: "Standard homodyne v2 configuration template"
  analysis_mode: "static_isotropic"
  parameter_count: 3
  created_by: "homodyne-config"