# Homodyne v2 Minimal Configuration: Laminar Flow Analysis
# ========================================================
# Minimal working configuration for nonequilibrium laminar flow analysis.
# 7-parameter model: D₀, α, D_offset, γ̇₀, β, γ̇_offset, φ₀
# 
# This template contains only the REQUIRED sections and parameters
# needed for full nonequilibrium homodyne analysis to work.

# REQUIRED: Analysis mode specification
analysis_mode: "laminar_flow"

# REQUIRED: Core physics parameters for analysis
analyzer_parameters:
  # Time step between correlation measurements (seconds)
  dt: 0.1
  
  # Frame range for analysis (larger range needed for 7-param fits)
  start_frame: 1
  end_frame: 2000

# REQUIRED: Data file locations
experimental_data:
  # Path to directory containing data files
  data_folder_path: "./data/sample/"
  
  # HDF5 data file name
  data_file_name: "your_data.hdf"
  
  # Phi angles file (required for laminar flow analysis)
  phi_angles_path: "./data/phi_angles/"
  phi_angles_file: "phi_list.txt"

# REQUIRED: Analysis mode settings
analysis_settings:
  # Disable static mode for laminar flow
  static_mode: false
  
  # Model description for 7-parameter analysis
  model_description:
    type: "nonequilibrium_laminar_flow"
    parameters: 7

# REQUIRED: Initial parameter values
initial_parameters:
  # Parameter names for 7-parameter laminar flow model
  parameter_names: ["D0", "alpha", "D_offset", "gamma_dot_0", "beta", "gamma_dot_offset", "phi_0"]
  
  # Initial values for optimization
  values: [1.0e-6, 0.8, 1.0e-8, 0.1, 0.5, 0.01, 0.0]

# REQUIRED: V2 optimization configuration
optimization:
  # Variational Inference (primary method)
  vi:
    enabled: true
    max_iterations: 2000  # More iterations for complex 7-param model
    learning_rate: 0.005  # Lower learning rate for stability
    convergence_tolerance: 1e-7
  
  # MCMC sampling (essential for 7-param uncertainty quantification)
  mcmc:
    enabled: true
    num_samples: 4000     # More samples for 7-param posterior
    num_warmup: 2000
    num_chains: 4

# REQUIRED: Angle filtering for laminar flow
optimization_config:
  angle_filtering:
    enabled: true
    # Multiple angle ranges for comprehensive flow analysis
    target_ranges:
      - min_angle: -30.0
        max_angle: 30.0
      - min_angle: 60.0
        max_angle: 120.0
      - min_angle: 150.0
        max_angle: 210.0
      - min_angle: 240.0
        max_angle: 300.0
    fallback_to_all_angles: true

# REQUIRED: Parameter bounds for 7-parameter model
parameter_space:
  bounds:
    # Diffusion parameters
    - name: D0
      min: 1.0
      max: 1000000.0
      type: TruncatedNormal
      prior_mu: 10000.0
      prior_sigma: 1000.0
      unit: Å²/s

    - name: alpha
      min: -2.0
      max: 2.0
      type: Normal
      prior_mu: -1.5
      prior_sigma: 0.1
      unit: dimensionless

    - name: D_offset
      min: -100
      max: 100
      type: Normal
      prior_mu: 0.0
      prior_sigma: 10.0
      unit: Å²/s
    
    # Additional parameters for laminar_flow mode
    - name: gamma_dot_t0
      min: 1.0e-06
      max: 1.0
      type: TruncatedNormal
      prior_mu: 0.001
      prior_sigma: 0.01
      unit: s⁻¹

    - name: beta
      min: -2.0
      max: 2.0
      type: Normal
      prior_mu: 0.0
      prior_sigma: 0.1
      unit: dimensionless

    - name: gamma_dot_t_offset
      min: -0.01
      max: 0.01
      type: Normal
      prior_mu: 0.0
      prior_sigma: 0.001
      unit: s⁻¹

    - name: phi0
      min: -10.0
      max: 10.0
      type: Normal
      prior_mu: 0.0
      prior_sigma: 5.0
      unit: degrees

# OPTIONAL: Enhanced logging for complex analysis
logging:
  enabled: true
  level: "INFO"
  console:
    enabled: true
  file:
    enabled: true
    path: "./logs/"
    filename: "laminar_flow_analysis.log"

# OPTIONAL: Metadata
metadata:
  config_version: "2.0"
  description: "Minimal laminar flow configuration"
  analysis_mode: "laminar_flow"
  parameter_count: 7
  complexity: "high"