name: âš¡ Optimized Fast CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'homodyne/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/ci-optimized.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'homodyne/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/ci-optimized.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUNBUFFERED: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_COLOR: 1
  FORCE_COLOR: 1

jobs:
  # Pre-flight checks and change detection
  detect-changes:
    name: ðŸ” Detect Changes
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      core-changed: ${{ steps.changes.outputs.core }}
      tests-changed: ${{ steps.changes.outputs.tests }}
      config-changed: ${{ steps.changes.outputs.config }}
      docs-only: ${{ steps.changes.outputs.docs-only }}
      performance-tests: ${{ steps.changes.outputs.performance }}
      gpu-tests: ${{ steps.changes.outputs.gpu }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            core:
              - 'homodyne/core/**/*.py'
              - 'homodyne/optimization/**/*.py'
              - 'homodyne/data/**/*.py'
            tests:
              - 'tests/**/*.py'
            config:
              - 'pyproject.toml'
              - 'requirements*.txt'
              - '.github/workflows/*.yml'
            docs-only:
              - 'docs/**'
              - '*.md'
              - 'README.*'
            performance:
              - 'homodyne/optimization/**/*.py'
              - 'tests/performance/**/*.py'
            gpu:
              - 'homodyne/device/**/*.py'
              - 'tests/gpu/**/*.py'

  # Fast linting and formatting (runs in parallel)
  lint-and-format:
    name: ðŸ§¹ Lint & Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: detect-changes
    if: needs.detect-changes.outputs.docs-only != 'true'
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Use 3.12 for fastest setup
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: âš¡ Install linting tools only
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: ðŸŽ¨ Check formatting (ruff)
        run: ruff format --check --diff homodyne/ tests/

      - name: ðŸ” Lint code (ruff)
        run: ruff check homodyne/ tests/ --output-format=github

  # Build package and cache dependencies
  build-and-cache:
    name: ðŸ“¦ Build & Cache
    runs-on: ubuntu-latest
    timeout-minutes: 8
    needs: detect-changes
    if: needs.detect-changes.outputs.docs-only != 'true'
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: pyproject.toml

      # Advanced dependency caching
      - name: ðŸ’¾ Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: deps-${{ runner.os }}-py3.12-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            deps-${{ runner.os }}-py3.12-
            deps-${{ runner.os }}-

      - name: ðŸ“¦ Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -e ".[test,dev]"

      - name: ðŸ”¨ Build wheel
        run: |
          source .venv/bin/activate || python -m pip install build
          pip install build
          python -m build --wheel

      - name: ðŸ’¾ Cache build artifacts
        uses: actions/cache/save@v4
        with:
          path: |
            dist/
            .venv/
          key: build-${{ github.sha }}-${{ runner.os }}

      - name: ðŸ“¤ Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ github.sha }}
          path: dist/*.whl
          retention-days: 1

  # Fast unit tests (parallel with build)
  unit-tests:
    name: âš¡ Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [detect-changes, build-and-cache]
    if: needs.detect-changes.outputs.docs-only != 'true'
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: ðŸ”„ Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: deps-${{ runner.os }}-py3.12-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('requirements*.txt') }}

      - name: ðŸ“¦ Quick install
        run: |
          source .venv/bin/activate || {
            python -m pip install --upgrade pip
            pip install -e ".[test]"
          }

      - name: ðŸ§ª Run unit tests
        run: |
          source .venv/bin/activate || python
          python -m pytest tests/unit/ \
            -v \
            --tb=short \
            --maxfail=5 \
            -x \
            -m "not slow and not gpu" \
            --cov=homodyne \
            --cov-report=xml \
            --junit-xml=junit-unit.xml

      - name: ðŸ“Š Upload coverage
        if: success()
        uses: codecov/codecov-action@v4
        with:
          file: coverage.xml
          flags: unit-tests
          name: unit-tests

      - name: ðŸ“¤ Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: junit-unit.xml

  # Integration tests (depends on unit tests passing)
  integration-tests:
    name: ðŸ”— Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [detect-changes, unit-tests]
    if: |
      needs.detect-changes.outputs.docs-only != 'true' &&
      (needs.detect-changes.outputs.core-changed == 'true' || github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: ðŸ”„ Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .venv/
            dist/
          key: build-${{ github.sha }}-${{ runner.os }}

      - name: ðŸ§ª Run integration tests
        run: |
          source .venv/bin/activate
          python -m pytest tests/integration/ \
            -v \
            --tb=short \
            --maxfail=3 \
            -m "not slow and not gpu" \
            --junit-xml=junit-integration.xml

      - name: ðŸ“¤ Upload integration results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: junit-integration.xml

  # Performance tests (conditional, runs in parallel)
  performance-tests:
    name: ðŸƒ Performance Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [detect-changes, unit-tests]
    if: |
      needs.detect-changes.outputs.performance-tests == 'true' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      contains(github.event.head_commit.message, '[perf-test]')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need history for performance comparison

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: ðŸ”„ Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .venv/
            dist/
          key: build-${{ github.sha }}-${{ runner.os }}

      - name: ðŸ“¦ Install benchmark dependencies
        run: |
          source .venv/bin/activate
          pip install pytest-benchmark

      - name: ðŸƒ Run performance tests
        run: |
          source .venv/bin/activate
          python -m pytest tests/performance/ \
            -v \
            --benchmark-only \
            --benchmark-json=benchmark.json \
            --benchmark-compare-fail=min:20% \
            -m "not gpu"

      - name: ðŸ“Š Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        if: github.ref == 'refs/heads/main'
        with:
          tool: 'pytest'
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

  # Multi-platform tests (only on main or with full-ci flag)
  cross-platform:
    name: ðŸ–¥ï¸ Cross Platform
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            python-version: "3.12"
          - os: macos-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.10"  # Minimum supported version
          - os: ubuntu-latest
            python-version: "3.13"  # Latest version
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    needs: [detect-changes, unit-tests]
    if: |
      github.ref == 'refs/heads/main' ||
      contains(github.event.head_commit.message, '[full-ci]') ||
      needs.detect-changes.outputs.config-changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: ðŸ”§ Install system deps (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential

      - name: ðŸ”§ Install system deps (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install gcc

      - name: ðŸ“¦ Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      - name: ðŸ§ª Run core tests
        run: |
          python -m pytest tests/unit/test_data_loader.py tests/api/ \
            -v --tb=short --maxfail=3 -x -m "not slow"

  # GPU tests (conditional)
  gpu-tests:
    name: ðŸŽ® GPU Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [detect-changes, unit-tests]
    if: |
      needs.detect-changes.outputs.gpu-tests == 'true' &&
      github.repository_owner != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: ðŸ”„ Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: .venv/
          key: build-${{ github.sha }}-${{ runner.os }}

      - name: ðŸŽ® Simulate GPU tests (CPU fallback)
        run: |
          source .venv/bin/activate
          # Run GPU tests with CPU backend for validation
          JAX_PLATFORM_NAME=cpu python -m pytest tests/gpu/ \
            -v --tb=short -m "not requires_gpu" \
            --maxfail=2

  # Final validation and deployment readiness
  deployment-check:
    name: ðŸš€ Deployment Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [lint-and-format, unit-tests, integration-tests, build-and-cache]
    if: |
      always() &&
      needs.lint-and-format.result == 'success' &&
      needs.unit-tests.result == 'success' &&
      (needs.integration-tests.result == 'success' || needs.integration-tests.result == 'skipped')
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ”„ Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel-${{ github.sha }}
          path: dist/

      - name: ðŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: âœ… Validate package installation
        run: |
          pip install dist/*.whl
          python -c "import homodyne; print(f'âœ… Package imported successfully: v{homodyne.__version__ if hasattr(homodyne, \"__version__\") else \"dev\"}')"

      - name: ðŸ“Š Generate summary
        run: |
          echo "## ðŸŽ¯ CI Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "âœ… **Linting & Formatting**: Passed" >> $GITHUB_STEP_SUMMARY
          echo "âœ… **Unit Tests**: Passed" >> $GITHUB_STEP_SUMMARY
          echo "âœ… **Package Build**: Passed" >> $GITHUB_STEP_SUMMARY
          echo "âœ… **Installation**: Verified" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Integration Tests**: ${{ needs.integration-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Performance Tests**: ${{ needs.performance-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Cross-Platform**: ${{ needs.cross-platform.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_Ready for merge! ðŸŽ‰_" >> $GITHUB_STEP_SUMMARY