name: Quality Checks

on:
  # Run only on main branch pushes or manual trigger
  push:
    branches: [main]
    paths:
      - 'homodyne/**/*.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/quality.yml'
  workflow_dispatch:

env:
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUNBUFFERED: 1

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Security checks
        run: |
          # Check if bandit is available
          if command -v bandit &> /dev/null; then
            echo "Running bandit security scan..."
            bandit -r homodyne/ -ll || echo "⚠️ Bandit scan completed with warnings"
          else
            echo "Installing bandit..."
            pip install bandit
            bandit -r homodyne/ -ll || echo "⚠️ Bandit scan completed with warnings"
          fi
          
          # Vulnerability check (continue on error)
          if command -v pip-audit &> /dev/null; then
            pip-audit --desc || echo "⚠️ Vulnerability scan completed with warnings"
          else
            echo "Installing pip-audit..."
            pip install pip-audit
            pip-audit --desc || echo "⚠️ Vulnerability scan completed with warnings"
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan
          path: |
            bandit-report.json
          retention-days: 30