# Configuration file for the Sphinx documentation builder.
# Homodyne.0+ Documentation

import os
import sys
from pathlib import Path

# Add the parent directory (containing homodyne package) to Python path
sys.path.insert(0, str(Path("..").resolve()))

# -- Project information -----------------------------------------------------
project = "Homodyne"
copyright = "2025, Wei Chen, Hongrui He - Argonne National Laboratory"
author = "Wei Chen, Hongrui He"

# Get version dynamically from package (matching the test expectation)
try:
    from homodyne import __version__ as _pkg_version

    # Extract base version (before any .post or +dirty suffixes)
    version = _pkg_version.split(".post")[0].split("+")[0]
except ImportError:
    version = "2.22.0"  # Fallback for builds without package installed
release = version

# Project metadata
project_description = (
    "JAX-first high-performance XPCS analysis for nonequilibrium soft matter systems"
)
github_url = "https://github.com/imewei/homodyne"
doi = "10.1073/pnas.2401162121"
institution = "Argonne National Laboratory"

# -- General configuration ---------------------------------------------------
source_encoding = "utf-8"

extensions = [
    "sphinx.ext.autodoc",  # Auto-generate API docs
    "sphinx.ext.autosummary",  # Summary tables
    "sphinx.ext.napoleon",  # NumPy/Google docstrings
    "sphinx.ext.viewcode",  # Source code links
    "sphinx.ext.intersphinx",  # Cross-project links
    "sphinx.ext.mathjax",  # Math rendering
    "sphinx.ext.doctest",  # Doctest support
    "sphinx.ext.todo",  # Todo items
    "sphinx.ext.coverage",  # Coverage tracking
    "myst_parser",  # Markdown support
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    # Internal development documents not for public docs
    "performance/*",
    "specs/*",
    "analysis/*",
    "architecture/*",
    "plans/*",
]

# The default language to highlight source code in.
highlight_language = "python3"

# -- Options for autodoc extension -------------------------------------------
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
    "ignore-module-all": True,
    "no-index": True,
}

# Include __init__ methods in class documentation
autodoc_class_signature = "separated"

# Type hints configuration
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autodoc_preserve_defaults = True

# Mock imports for dependencies that might not be available during build
# arviz is optional and may not be installed in CI environments
autodoc_mock_imports: list[str] = ["arviz"]

# -- Options for autosummary extension ---------------------------------------
autosummary_generate = True
autosummary_imported_members = False

# Suppress warnings for autogenerated files — consolidated in extension config section below

# -- Options for Napoleon extension ------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

# -- Options for intersphinx extension ---------------------------------------
_online_intersphinx = {
    "python": ("https://docs.python.org/3", None),
    "jax": ("https://jax.readthedocs.io/en/latest/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "numpyro": ("https://num.pyro.ai/en/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

# Default to offline builds in CI/air-gapped environments; opt in with SPHINX_OFFLINE=0
intersphinx_mapping = _online_intersphinx.copy()
if os.environ.get("SPHINX_OFFLINE", "1") == "0":
    intersphinx_disabled_domains: list[str] = []
else:
    intersphinx_disabled_domains = list(_online_intersphinx.keys())
intersphinx_timeout = 1

# -- Options for MathJax extension -------------------------------------------
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
mathjax3_config = {
    "tex": {
        "inlineMath": [["$", "$"], ["\\(", "\\)"]],
        "displayMath": [["$$", "$$"], ["\\[", "\\]"]],
    }
}

# -- Options for MyST parser -------------------------------------------------
myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "deflist",
    "html_admonition",
    "html_image",
    "colon_fence",
    "smartquotes",
    "replacements",
]
myst_heading_anchors = 3

# -- Options for HTML output -------------------------------------------------
html_theme = "furo"

html_theme_options = {
    "navigation_with_keys": True,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": github_url,
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            """,
            "class": "",
        },
    ],
    "source_repository": github_url,
    "source_branch": "main",
    "source_directory": "docs/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom CSS files
html_css_files = [
    "custom.css",
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = "_static/logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = "_static/favicon.ico"

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, links to source code are shown. We disable this for cleaner docs.
html_show_sourcelink = False

# Output file base name for HTML help builder.
htmlhelp_basename = "homodynedoc"

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "10pt",
    "preamble": r"""
\usepackage{amsmath}
\usepackage{amssymb}
""",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        "index",
        "homodyne.tex",
        "Homodyne Documentation",
        "Wei Chen, Hongrui He",
        "manual",
    ),
]

# -- Options for manual page output ------------------------------------------
man_pages = [("index", "homodyne", "Homodyne Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------
texinfo_documents = [
    (
        "index",
        "homodyne",
        "Homodyne Documentation",
        author,
        "homodyne",
        "JAX-first high-performance XPCS analysis for nonequilibrium soft matter systems",
        "Miscellaneous",
    ),
]

# -- Options for Epub output -------------------------------------------------
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright
epub_exclude_files = ["search.html"]

# -- Extension configuration -------------------------------------------------
# Suppress specific warnings to reduce noise
suppress_warnings = [
    "misc.highlighting_failure",
    "myst.xref_missing",
    "autosummary.import_cycle",
    "toc.not_included",
]

# -- Todo extension configuration --------------------------------------------
todo_include_todos = True
