name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[docs]  # Use the package's doc dependencies
        
    - name: Build documentation
      run: |
        cd docs
        make clean
        make html
        
        # Verify build success
        if [ ! -f _build/html/index.html ]; then
          echo "❌ Documentation build failed - index.html not found"
          ls -la _build/html/ || echo "No _build/html directory"
          exit 1
        fi
        
        echo "✅ Documentation built successfully"
        echo "📊 Build statistics:"
        echo "  Total HTML files: $(find _build/html -name "*.html" | wc -l)"
        echo "  Total size: $(du -sh _build/html | cut -f1)"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy documentation ${{ github.sha }}'
        
    - name: Success message
      run: |
        echo "🎉 Deployment successful!"
        echo "📖 URL: https://imewei.github.io/homodyne/"
        echo "⏰ Note: GitHub Pages may take 5-10 minutes to update"
